### ISSUE TITLE
undefined function chgrp()

### ISSUE THREAD

**Issue by cpken** [pk-fr/yakpro-po#102]
# why?

```shell
$ sudo yakpro-po

Info:   Using [/usr/local/yakpro-po/yakpro-po.cnf] Config File...
Info:   yakpro-po version = 2.0.14
Info:   Process Mode            = directory
Info:   source_directory        = [/www/wwwroot/my.test/]
Info:   target_directory        = [/www/wwwroot/test_demo]
PHP Fatal error:  Uncaught Error: Call to undefined function chgrp() in /usr/local/yakpro-po/include/functions.php:305
Stack trace:
#0 /usr/local/yakpro-po/yakpro-po.php(108): obfuscate_directory()
#1 {main}
  thrown in /usr/local/yakpro-po/include/functions.php on line 305

Fatal error: Uncaught Error: Call to undefined function chgrp() in /usr/local/yakpro-po/include/functions.php:305
Stack trace:
#0 /usr/local/yakpro-po/yakpro-po.php(108): obfuscate_directory()
#1 {main}
  thrown in /usr/local/yakpro-po/include/functions.php on line 305
Info:   [variable         ] scrambled   :        0
Info:   [function_or_class] scrambled   :        0
Info:   [method           ] scrambled   :        0
Info:   [property         ] scrambled   :        0
Info:   [class_constant   ] scrambled   :        0
Info:   [constant         ] scrambled   :        0
Info:   [label            ] scrambled   :        0
```

can you tell me why, How should I solve it？

```shell
$ php -v
PHP 8.0.20 (cli) (built: Jun 10 2022 10:30:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.20, Copyright (c) Zend Technologies


$ php -m
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
swoole
sysvsem
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
```

**Comment by cpken** [comment]
finish
